service: Blossomdlm
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  stage: prod
  timeout: 15
  region: us-east-2

functions:
  # api:
  #   handler: lambda.getLeaderboard
  #   events:
  #     - http:
  #         path: /leaderboard/{classId}
  #         method: GET
  #         cors: true
  api:
    handler: lambda.handler
    events:
        - http:
            path: /
            method: ANY
            cors: true
        - http: 
            path: /{proxy+}
            method: ANY
            cors: true          
        - schedule:
            rate: cron(0 1 * * ? *)
            enabled: true
    environment:
          DB_URL: mongodb+srv://Nabh:Nabh123@cluster0.rbcigf9.mongodb.net/nabh-dlm
          
