service: Blossomdlm
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  stage: production
  timeout: 15
  region: us-east-2

functions:
  api:
    handler: lambda.handler
    events:
        - http: ANY /{proxy+}     
        - http: ANY /
#         - schedule:
#             rate: cron(0 1 * * ? *)
#             enabled: true
    environment:
          DB_URL: mongodb+srv://NabhDLM:Nabh%408817@cluster0.lvldd22.mongodb.net/nabh_dlm_testing
          
