service: Blossomdlm
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  stage: production
  timeout: 15
  region: us-east-2




functions:
  api:
    handler: lambda.handler
    events:
        - http: ANY /{proxy+}     
        - http: ANY /
        - schedule:
            rate: cron(*/5 * * * ? *)
            enabled: true
    environment:
          DB_URL: mongodb+srv://Nabh:Nabh123@cluster0.rbcigf9.mongodb.net/nabh-dlm
  

